[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "d5b174d9d585fb6316aec5970807b676ca13dbef"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e6647ab380f7e8ec3442e7fb4011462e8db6dfde5978d058b591e36a7a6bde55"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.1+1/LibUnwind.v1.3.1.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "bfa81db914da08bb3f7a5f1a1c2783ac85754be2"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "c9140dbd50a1fa29fcf88c2fb169d97e07f57b75923a9739e422b60daf9b725d"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.1+1/LibUnwind.v1.3.1.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "1443e82b5c5f067d08cc37abd18ec3caf8d817af"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "84688a43cb21293db5dc7a75edaaca3729f5a7f8d81b0624326942cf4cd009d9"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.1+1/LibUnwind.v1.3.1.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "8595550c71b724b1a419b5a3cb666adc514e338f"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "a4fb48aaaa34b94ac040bee1fed69334821bc0cc84cf79366bbb0578f1d48266"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.1+1/LibUnwind.v1.3.1.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "adaa7a427dca741f6f48b393d2b1d9a7fb9f99c3"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "faacbae066854e30d5ad108a802f198762db1fa156dc8edf9d286cbc91c92210"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.1+1/LibUnwind.v1.3.1.x86_64-unknown-freebsd11.1.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "0bb8d858b89485a330fed0092f85c0613aeb6b78"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "d000571db46e34e35a6f4b3b558c31ae042e50de9f647f287bea84d5c45af41d"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.1+1/LibUnwind.v1.3.1.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "a52abcc9322ca8a626c22bbf0ae5c12dd05ab4dc"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "7401b7ea02218a7d182af1251611cb067ab15ba2d6db72416cb3158ffdc4f80c"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.1+1/LibUnwind.v1.3.1.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv7l"
git-tree-sha1 = "dc9af9bf4b17d97dd2628dc70f671017ef36b4a1"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "479eeef5a780eea2b2d8452b982ebdf197f95a7a564c041afcac9fe580e3310e"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.1+1/LibUnwind.v1.3.1.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "022f08f36d4cd2bea96dbea2cce456771d5b4e18"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "0e0af2d14b46fd8a2b7c972f29a99a55bf2ce4d46d1ced20696b960f381c4f39"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.1+1/LibUnwind.v1.3.1.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv7l"
git-tree-sha1 = "a920f2ec5a59e4454db6cf863a626123dc8c3aff"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "28156560e69ee57e8186b7cfc31944279bd7d9740b83bc717b360918299e43bd"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.1+1/LibUnwind.v1.3.1.armv7l-linux-musleabihf.tar.gz"
