[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "45c4a0db994b825ca96c0670966e67db2d2e241e"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e21efd89cde5276fc12e86a4b1461fe00a95839167d0acdeecc8c975db94a9c7"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "cd6de6395c6c627f2d6dd76fe6ad46f6dac3f52f"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "9d7656c0cced8035ddb15e94a06829b941a78b21df29f39ae417cab2ec84a3dd"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a031c99f2b4cbd480f773e264e3d856c87dd45d2"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "c075737dff7f29f7f8d91f328d96508b222e941da7e3b8edd386bddbede6c1c9"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f94291b29a74316c97bcbea18adab24489864cc2"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "270d31b048ddfa7502d906c595a9978024ac1401efb763a885c4cf561c639dab"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "105959d2dfec91f6edf706316c5cf4afad9f1149"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "ad682f0146dd8657c544dd37cf998c9c7eac40f72dd1cdbf538aec1aa84f415c"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a0fbe772495f430c2a4f939c5ff8248bcc9831ac"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "4ee9ec46355f5848eb120f151d29d139168314d877b6e61e7b6f45c9c29e4677"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "3e34cec4e62dcda05ee2a8143263a301026fa510"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "c79180c5b7d9f20e8bedd635675cf183421ee19845b4eff666e25d48bcbc5bb1"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "40e76cdcd4ab56bebe5aafd00a985612fe4a360b"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "a29f30ee16e5dbf6fc1306f81caa4f37c21ed67c8a99ce3940246d1c4bda0e85"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "40950676882c9de74fd1ad85b3ef25053a8f1178"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "1bc97facbd3f6cf9c6063051077b1e2b72869110093ffdf5367dbf22917676e3"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "c586c9e6290d7a126c825332ee465c20a817bc5a"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "1f5b209b517776518b2d1362751da2e38a551cc757d87ddb47ccafa560f6bce7"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "a985295bb99d57194a04a42f11824900bbf599fb"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "5922306185240976a7cc3e01b095f1fec56ec1335877975fa354c6ff8613fc47"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "ebfea5da0c46c8c4e7f96dbbc29c7bb67395a92d"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "fcaaaee47031255f0140251201a820b8e52ab29a85db8a71e31cecb6ef4c6dc5"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+3/LibUnwind.v1.3.2.x86_64-unknown-freebsd.tar.gz"
