[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "c178f06bb10a199ab116904b97fce4f821ba89b4"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "90e19c7ce4f6f1c518eab3d68464366bef60b76e8a14fca1ab3e8b209fba997e"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "1ba4e1aee2ec1142a810e86ddfa15a74b4f7cdcd"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "a08aac4ae8b57728bdcabe65e9a5dbc66ae30a58aa6d2ae3c49ba491c8473060"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0f71371a44600d2371bd6b75449db051e57f1e1f"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "fd5afc47786b5f41718d65e4ce41017485178bc18dbc20adb78448d48ca12f84"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ca897acefa10a8b469bfd5157422f90e0ede62bd"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e44a365305894d720e5ecd9b0472810c07a53b125f3d7d0177c24eed4ed20c9c"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3900d53b1f48dbe9c12acdc011dc46b5de4d0696"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "70565905775e55ce16768536043ea1b12c936101ca88c84a688faf49b7cfc1b6"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3a45eec51fb748bf1cebafad81dceff90cbe22eb"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "3c2d4a1546109113bd6af9167fbca493e55cd0d25944e4475241c4bd33b12fc6"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "12e9a545da463abdc0d34d92eb7b7023e0a1d46a"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "4cd4eb12b64a41c1fb418c18d1dd6b2cee30af7061ab51f0ef84df1aa338c9df"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "20beda16df5a7bf38770851f97d2f0ad7ba0b34a"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "bfd399d4ca945140e66efdf6ec5be41258e6fdc83a27b3faf675d689952517c8"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "c8a2909cfee848ebcfd8b39796dc6d605cef4952"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "9ad87249811743b2479efa2bdb759ff2ca0f8dd642e257d128e595a27e71ae16"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "102b4c5a82716ec4aad98a1fb418bd8c599e8b8f"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "5b1cd3ec23703e0456467fd447bdb212bb7d7f574830d4a3bb29b7955528e8d7"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "de3857373ff1519a83e36e7938b00e7c15b163a5"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "988355da82290670c6c00bd77760f652b882264b01d2296bf04f47ecdea6cb5f"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "cb105be00454ce6c1dd5d42232ba14ddf4c7c4e8"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "b05cfb03a21927f31bf097dbc38b9a6b78f4a7270ce53930e05e5d83de48f2dd"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+4/LibUnwind.v1.3.2.x86_64-unknown-freebsd.tar.gz"
