[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "5854a1bcc27504bfc5c482ce906b81ca6f17bdaa"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "123c52da12e79dfbcae339cc21bc1d300b3768600faed29995dd3ff2da567940"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "abf37f606062bcd3ac6740ff1d5d69d0f0233664"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "9a4702e434170cb6103a5faf77377659bc8e182efcef48927588b2be81e83194"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "73fb31c441dd66645ceb2bf002a3e28377efea6d"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "3bd8cf49308d360691badbd92e8f100e23668e52c1e7d8c7a5725e4b36662a8e"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e0640e99b6db595c4cc5f33b9991b1652369b5f"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "046569259e630b57df4c5ea2e2b46d04b0971a8475ec72531df5c366709f1d1a"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1f388af1442b5adcb0e1389f41d2a98a3144f2bb"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e6346328d5809801e16cd010d337003603751d37caca11f11bc54b797fc8888b"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6228b65ad53377b9594f1a09c50ad04b536afa79"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "d5d7410333a56869448d24fea7649d62cca443311f48a236ddbb04276717e686"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "fa004f27d27452d8fb4af19b83464b1812b437f6"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "4278e45d32f7d8ad8aa5e5df4a7f8e73b87e284c344962caa227f598443c517b"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "a1271cacdba7fc89c4f91e04088abf6bf6964a48"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "816ee92724a3f4ab3255763d3dd106d5e69e7ccef584b26cc9fb4fe1559e7c5d"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "1e0a19fe5b51ebb15677510a4a5c7e24381b34ac"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "a80443f77109f16bff5cb8f9a7cebf5342aef1fa3966b86a8ea1433468595e30"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "345098c4e93aef02ef994cce1824f257d412057d"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "bc604b1680c93bdc9a2084db0741842a66c8aa006f7e4ff0331746e8b9e493c2"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "e8f2c3d9ad3efcb5158b0294a8f67d599a02d054"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibUnwind.download]]
    sha256 = "a2bed83b0e92ea79aff5ad42c4608b001ab5bfabd1fc15d7c43b9674d9fe863c"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "2b7185e581fde90762831b561a6436a8439bf87f"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "52ff35478662bf5aa2169245c2c7d4a361c530d8c70bd47751844d65b3c782cf"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "bd89469291baf54381c1401f60fe4ac6a3a89a91"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "9efe5ad27c1ba5b046b392a60a7aef6a99cf1c6e0822c0cce4c9256a313960c5"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.7.2+0/LibUnwind.v1.7.2.x86_64-unknown-freebsd.tar.gz"
