[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "3e7690f323b00fb254398ed19c4dad7b1896e01a"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "784cde879a1979a051fa7f21031ada479f4d9f13ddbfe3fa2aa6e1eb1f9bfebe"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "dc64d0bc8e685a3082de35ab95685550438d4f3f"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "fc71abcb738488d0ce68549a1bf207cb43921aba2c8606ecdc7668b19c128f9c"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56618f871b194f4a161250892714685aeb3d13f8"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "d6122d8e6cce09fd612d5b006b1f4263cc1070767afb8a86e53e8a72641ef685"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ca9f56084902a2756881c28be93fc0b37698eecb"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "b40ef1afbb4f886e5598a56ac85e72b5dc406e5a39d1c8342a11f32092a3dccc"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "74d29281acb1e2a40990d3d3cd5ed1aabd31b532"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "7bd924bd8de85edb626a02b0a65cf1bc27c0700179df4a0ad659568a9a4bc09b"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "39b89f475983d9acdae5d49be1a14e7e32630d65"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "2616909429f9d37aa1444d8e52def181ec4d14049f06b2f3bbcf56fb445ead07"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "2168b7d6dacd45ef334b2b7a4c4f1780b2f716bb"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "72d010e820b45c45790aa95078ecdf1c226f96b6138b3c21855b0f8aedd6e49e"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "cb013612cf4db58547d90e025cef75707bbdd77b"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "aa13a96ae53f401b81604ae63f58c72a47f56acdd7c106150e5642d56f4b2911"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "445d48356b07803c5667e56ada9f19390b9ba4b2"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e147a5c05c819c4092ffd78863af310bc13cae7e76b3bac111c7616880d58efd"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "6fdf8fc95fc9f34ddbbc9fe77e7687696aee3185"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "415bea5ca31043a705e2e7c6f66b91144ddbe86f70e73dd8c5e4e2a1af4e77e6"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "10777eac7ec8a6ccb824248cda4c824be6cacc31"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "82d1d2dc878e9bf79d9b5f46351acd45b15c680ca69d204a28294a37f9b8ce9d"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "138526e66483620cbb1227ce5663e6dbf9e2fba9"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "7982e5bd3da89fbac5d62afa57c46886367f4e51bd3f693dcab2662db4342923"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+0/LibUnwind.v1.5.0.x86_64-unknown-freebsd.tar.gz"
