[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "d395fafa16d49448a67f5661ccd5c328ae3d7660"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "ab77e7c388034aa488570bde8c18a820009e0d63eeb2e757ff19229a9b00e418"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "615f7c650c63bdbdd4976322c9dbe5b48403a948"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "2964f3a915f138c2a04b378da394b16d61ba382edff4fac193b62c0813101b14"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "304a9deed65791a7e3b1fc253ba0e7bc69677823"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "5393b333a968633becd5590619bcc8f1e3fbe24eaef34db6f23184a2b50facc6"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cb5cb243397c8a31564f6f92821ec4f69c3e1bf1"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "494b31d3a8ebfdae75663204f9777a93a565511f8f2f91c1254f80c282836784"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "933348097f7c30baa3684a4a90afa388ff5d3f17"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "af8df1991fb7e77f90b99fa5c3ed5a5a3598b58594d75ab1c11847fb9c60fdd9"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3979a1cdec5cb3dd7c1da47bc8c5d1cfe3498bc2"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "1269659b1a4a53d5598ac83205848972429ee46c65015c567bd12d2ccee4ad12"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "a811395dceec3197fcc07dfa6d74c066745358fc"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "6865e8cc29903603b8554d455c8954c20d701ddadff68757f00dc7426487949b"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "614dd648f3cfe01f525547035c6a7f2df911679e"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "18f48afc393379fcd2c69610df5943c95c7f3c71c3baf119599c3ff729ddde0a"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "91598b357c50b9b626a30153208fd421846c5a53"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "d6df0a14db466736b173ba886ceabcee7ffaef50f60b9f6cb3a34a9d4e111e5b"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "49dcaba37f9b6be0ff14b8f46a5e7c11adab315a"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "a1276908df41ca6dc7c77bc05c8cce5d2fd261897a16325c70c5028284fa51c5"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "fffa7530c6f4f48b290e4be61aba4f568b20e1b9"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "88cb5e472734e712e6b9ffc5d080f39cd5315694a3b7663fce75a415d45b1c8f"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "0f4a4514d50bd08503e6de64306d8458a2cd3386"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "1b0c539b0a4dd8d53a0e1c78734fff788991ccce58d445351b481770748174a4"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+1/LibUnwind.v1.5.0.x86_64-unknown-freebsd.tar.gz"
