[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "e12ffe05c08d174c49198dc733031c62f5fcb574"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "ef343621b16bd50e29a08088a11a1b17fad4dcb680eb66db118121a3b07c5f21"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "d6d69b1cfa6f1c89282585b99e8367142d31dd25"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "2dc8553efec055f701a432090eddadd15e639e87daa02da464b2bb5fe89511e3"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "87890100e391037bfaf03f68a5d5ea3c87c91477"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "7ce345c27ced787006b26e03d524af11657c14ad87c7c09c5bd67ffa5d014a46"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0adcd1f59620722fb89f45a93b7d755ceb06ddbc"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e82a773b74c26a22eafb8b98e4270d1f92ad89ad002bf3ae8a4169137acdcef0"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cd3e3f0aeea079eeb34565f5267f946004b0d4c8"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "42fbba2ed4e5f8647e3f01eb1a5dbb56d79fb72990ff8f098231ca21c60f01f1"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e76768eb966b72389d42575aae7adf5f296b3839"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "34b696690c1fb13143502997ecaa24bd0fe3bfb4a991429fac259cf01c5cf7ef"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "5175478a2746d838b0fa423de0cc18de7edfd8ee"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "7de1e0fd492b616ec7f9c2f42cf81df4fa89da346aa08874b3a86a3fc2cfd24f"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "489ff67e7556ca0907dc2b97588dd328fa8bf93a"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "75fda254dcc32b656eb6264e943741ad61961246114c510010339b793006be97"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "7c622c3cc00ef4fe198ff40709a64ddf1b6822cb"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "f728e79f8909326944baa0616d66c0b1dc72c6594fb14f1748073e26311e14dd"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "0a1dbc2e3ea9002b9d19c4257479edbfbdefd84a"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "1be99b4b10e1f023b6d63eaf425a8ed45ab3d3bfff944362ede57eabeb54a847"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "f2cb8d0175c972656d866b341bf4bc9f2b7ec99b"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibUnwind.download]]
    sha256 = "dc3f8bcd33a41950e6e1f2cb9acfa767f7f8d4ec627b4e0d88150eac8e78f3fd"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "1e2f5178c9ce08160dceef1046639b34356cf3f0"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "b931984b8ea161d484c87425e66b0e9faa9714576d0cd35ceb145198aa4437cc"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "12a76b6168b54befb75a1548237f33ecfafa1773"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "906baafb7575a058a87de785372cd7f44a0df8ff75eeb4fa10404c61291127e5"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+1/LibUnwind.v1.8.1.x86_64-unknown-freebsd.tar.gz"
