[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "05a59cde20d7b037aaab60db855512f37a94b527"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "ef6226afa9dffcc2562539f9b1785d6218a3f6ae39fb36c74b8b363fd8ae5766"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "fb54f8aaeee19b5e69139cf82cfef5b928d379b1"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "c69ee42ef5b86013b910f82c137b54a77967d237e45c875063df6b63eb2eabce"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "718f8e6beaa944f5b5aae53478caa14ee63ab414"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "f40d2bc79ddbdf8f80857795fee79e0ca6529ff9dcdf0b3cd2d201c17167b1a1"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8d1fb78a1bfdd294cd911c46a05e1e33b05bb9a9"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "62739ac15f789e97393d2e1dea3f326074714b38c993263e2042e744f07d0867"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "44adf428c86fd885105b1bd46f598626be6f9f96"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "7a67ea0aadfa31281aca7877a12fed389436e4252f6fbbab26e84bf1dac78d01"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0df6e34969da487423572a6548c2d2944a8f42a6"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "5a9910f19aad74880343c42d921a4c9cb053e5f9ddfab58c0eeeda2b2081400e"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "506fd5c3c05b96fef724fcb83019118e68104186"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "f0ffdcb82ba9e977453bef50584036c8370e55e44bbc7e43f405a9e7065e0655"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "9a9df9eea69ead9239f0e8c66a3c8f5151844a07"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "b883b004e515a98001ab4818b843e46df4f23abfb6927a72be151805fca00e17"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "935d244e4123b487cd923b54596d8419b2f72dec"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "1181de3f5423fae0873064ffaef1e53e7874b2f47a3235201edb76dc100ad502"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "494339c61a47f472d5454e841fc0c7f9389ab470"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "40eb3941b1ae369b538964b4adc419f20a9a1099c76caf6d323aeb8faa1ac1d7"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "b1c83db72e3185d46cff20a5f8b93ab3e8929cb3"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "f12f6c5933dd84cac9ed0a71d96c026af143ea138984490de3347d10a7980a98"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "7995d30f8d1cfec22b92ddbf3e97ddc6e9364784"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "a12d0bebebab26fce930ed862466c66732d47a1e69c4360fedec70f74ec1170d"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+0/LibUnwind.v1.3.2.x86_64-unknown-freebsd.tar.gz"
