[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "f5bad708af6e3f0384f0878e56921b655e6d7e1b"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e64b089852843b9ac7c28f98148423a776237ecbe00eb2713325b4269fcbaf08"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "3d105db1f67be8153d08c14927dddccb8bdc92ea"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "d22c80755b274b3dafa1df45882f4571416140fcde3b67cc073ee2ff5551e862"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "49676b611cc622b31b119e3dead7614e4890e286"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "246d84b2db39ca05b61351b8696b4306912786fd7504e3cace7f6b936c867a17"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2efea045a6b1525c69bbf18f438ee7f9e25e1732"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "826a34e6a76bb59a9956a1605ae3ec30fbdae24f5f690263d560f0f13d1f0e80"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e258e272023d9963470a73227cab3c714ee3816"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "8de56f4b2e152c499b808f5dd40b1bf2e6eda925c103ff6da7f69e143ca3e69a"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7aca3cc2a38b580eb648341434e27f7d47806a83"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "8d1883e1eb5128d3b510fccd8c9dd9e540a10a385a327428edc479db8548edee"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "dcdaee2ee5c39e9fd25f103a99d7140b892bc858"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "06baa0f0529b1eba71a74f57c2e8e8dc8d1470a714bff078cce0f7be9bf28ea9"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "3d83dd53597971696fadc8eb9f698ec1d74dc670"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "91d576fa4b53b369c45ebfd95e11afcc9da393caaba9214dd727c45a04139cfe"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "1f3491ef22aef5e5c732aa895dadaa5748abe01b"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "56b69ad2d4802ad797ac3eab4a782e7da2c9144646ac25689f3189bbbcfcac0e"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "6d405520d88845a06ecfa09fc710ff05d39823c9"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "9dcbf2ea0203c629193e743539731ca731276f24087be0e1e597f49eabcb025e"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "aba51ea4defe8699434ce2226dcb40ec91e14424"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibUnwind.download]]
    sha256 = "b98c85bef454c4e187e11779b4523ffe68e9ec210f9ec312dcb0205c8b456d70"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "3b4fe99c55c3694a561401e3ca08f34586bc735b"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "d1cd2ae07fa546508d4de173676c800e232a047b1df022f25fc38eec7b889428"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "43ccf151d2a35ce0a467d585e167094b7fd826ed"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "99e10599b32d2cdb2e7fb90985228d82213eed46d5d3ef9f0b3049c5d19eea18"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.1+0/LibUnwind.v1.8.1.x86_64-unknown-freebsd.tar.gz"
