[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "55fb1705ea91a17958ec5a2e95a30f5245763105"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "9bd2bf1a14dc0f91665b22d951114be2ad3d8bb6e0334e45bcd7b38fd9d0100b"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "b2582ff83e31ce703b217ea57f41f29c20eb4580"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "bd005d251b26264ad715d21e4485435e07be068080173ec652e6d0d556c20b74"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "42067cf2ecd033e85faa2886b09b8357029ddf23"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e061382ba32c4c15969e5ada922ea7be54362e79fb872ecdddce29d4019f934d"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "773dd28ea05a4898ebbb8907a7eede6976f4c8b4"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "0215d8ecfd8ce1b0b2032aa96da3798d1b803c771d66526232b7126f9d542c04"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f44a86f741afe4a541e932c3709c630e3cbec5e7"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "b1dae096c83fbefd9aa80add5c2c84c19bfde2090d82ad4a31eecf5621aa2186"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d2be64952c0ac57bbbc3ac5c07f10e76fed101b8"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "eac5b6b331083fcdce27b192e254e4970b056813e1ca2e6e074792f6cc6b1183"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "45e15db051258cc31e891cff299356e19b3359a6"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "76166aef55fa37c0aef967f7bfa9c2c61affded45c775f94ac644acf94e7dbd9"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "b1b935041ffc182b40c0a7861f3fe15d11335909"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "43a496c68ed9824b47482d5942a48ab60d99531482e01ddc94835a6d662596af"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "72f2a2752c5b77b4f5839067fddd9c753baf866b"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "fd4ed7322fd18ea0c057a6e8edf1e0ce16911eefe1fdf8321662a7371e634d26"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "9e4b30892229792ecee8e88ce681dd26287b2264"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "559afa9a43c7cc5fff9cca27ef61b2b1d29bb46f9d7737ca5cc57e8aa4495479"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "6c32a0b98b07abf9091478d15498b89f9147bfc2"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "f82703dd177e43b2f64f7de5a560b70c1e1b5ce8698d3b445370ecc1c045577b"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "d80025c6c6b2d85e25b0ed648d0d221d4439f396"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "ff4ca377e159a0b4c14fa3a28c99c87ee6e13833e36606e43e6751d95b60f481"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+1/LibUnwind.v1.3.2.x86_64-unknown-freebsd.tar.gz"
