[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "4be6678ff1d8961139ed32b84565c06740818df1"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "3b0c609d639c365945c440a7d04cf5b7703e418f6374626b878a3bfd438d6ccf"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "2f4067aa9389b6b8e17f0a4f91eb16f0a013c053"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "a2df1b2f675a63f0087d73bd6676a1ecf4f1cbc63cac12523e19bdb398a666cc"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "818d22cd7d096f0a6944b018a377cdd2a6d5b75b"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "9b7a6597938d725d7531ecd9d78f5b4a6b6553c57c4ed4a478233e75e93f683c"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b48a0f32e89b3209719be341467696b511e7d13d"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "966daa37c419f3628488d9edd5118d8a723c7b23f8582ed4bb8b24cdaa959bcc"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0acc1c118b80ec0ddcabbbefd13e55d880fe1f47"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "dc0321555c07c4c4ddf6149dd048bef1226282da093b223b13fb0804c950923b"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b44c3aa0496aa6fdc7a8bd887d10e0074d738b07"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "7f71be95b74fc770f17e3f1a42c7d7224b260210138384d6c691f0538e5c0f74"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "fc6081c72996c90c02049b1c8d9a0376d9275467"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "5e54045792e79a47f1d73dbd2269e21d37e3b912918dfc945653e0259ff71969"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "cb54eda9b597406eccf9a388b11e2af0de94b446"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "fa57162cd6916f9d3b226b086081a8218a9bd5731e041077b7cab3da3baeb09a"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "178b7ec51ec93affb147225dca098c2953a98fe0"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "cc08ef85b1d39ee908f725cc6c8a4cf9a87ca2c342266a954f3b95cc677701bb"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "3be479c0056ac2c608fdf96808fb7a972865db30"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "4a374a6d30997c5bdb58a0b5524380ab7daca9096620f440144b697ca309e5a2"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "64ca4160768803378978909be3b039c34b9a4112"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibUnwind.download]]
    sha256 = "b364f3cc6eae6f852795caad1998d133d1ccd9f32d4e60c556c3eefec3f70d39"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "4200a3e8293843a52bb2ca8384eacee656806d45"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "ec74bc283853c0b395dd61c5afd9e070133be2e074ecbe51883016933bb36a42"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "6221afca50a7bbdd9e1630b440f7847a2815cde2"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "9e257d020e4277b278c2188a60b3f1c7cda6c8f431625cdd035c496fc6f0f58b"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+3/LibUnwind.v1.5.0.x86_64-unknown-freebsd.tar.gz"
