[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "8ebbad02e10e837cb7f7b0837ba127efcef7fe91"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "21b466c79246032e9b13851f5c68253168c88da090cb1c78f4e7503524242815"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "03fa5d3af6150e7ffa2cc6276b82c74bd186cbb4"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "4a8125a145698cf0c28c4703cf79abe9eaf356a00cc15ddf98a93f99f1ea440a"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "14064bd38964dc6b18d6fb7d5d2433aea0beea3b"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "ee16a9ea13085bd9ceeeb630d2834cfc3d7636dc942dfad5c99d6bddb2d78f96"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a88483fefb31943a0c6292bb112012b248b85b6f"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "07c0c1c83dd5ac467428729fae194ca219f216ad4fefd0fb4cc980e8e8ad4c46"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a3ca9a27675553f228f42c844aa2e7b1a0da51c1"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e4743ab36dfd5df0dc251b0f9b6080d98541b3178ebd6ab3e06922a6b3b6dc53"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d36b82fc94780c1c2ee7df1a54b5c754191f5b75"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "6593a61e3dadca9e9b9ec3f5606735c45bf292e3810493293588c2950dc0fd0e"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "795bb7f3d7b7292a4fee78b669e442404e8dbead"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e9fb836c53afc2c314d3be815c38ff97f8b10fa8c74b92cab1aee21a7776dab9"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "4b2882c03d55750dca9f4ece2c9d52718d4510cd"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "5ff681d69a4ae29108ff6aa263f94b8684c11ae9b89133e3491ca10245da7e16"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "5df7c40b4becdeb563594b2f554452c2f601e336"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "6785c21984e2b057249398da3dfd8c81a1169d6eee5eaa32bf979db422002e91"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "b85ed9767c180b3e01fe9d3d08c7d39536ca10ed"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "a1a638f86fb23e0cd30bd28065ab3639fb9977fbe7408bd9b78977bda949e5a5"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "fe3125491e83bb640ea61ecac8133c545875e226"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "bf9550ad3cf0c90e9c6c109c81b6119ea7014797eb1e16b6431f6524bba6ca8a"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "ef3d7dff5a702302d5ceec8717be8f95073b6303"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "bd15bfe5c0d87a2e09845d9ecfcca0527142038a56bedb7c017710f0240424d4"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.5.0+2/LibUnwind.v1.5.0.x86_64-unknown-freebsd.tar.gz"
