[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "7eb605977b70c1cc890e4b8f7ce01e74636010fa"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "efdf5392d693d2d9657ba9a03feb5d45ccc8f36ea7cd4109b66456251b83df2d"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "b76cf9e508009c976605ea584a9dbf133e6622cd"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "a540370f6260affaeb1ed5e6ef57772c54819e34f88f3778e82ae55d6d6c7cd8"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7540eaceec06eab2f78d2bca686a275536fe9f2f"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "1f3fe5569bbed25da42ee3c19514dad5f55cf7d51c2629b2086d135dac63ce5e"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "70c30c14087850017f9c724650656eade486ead7"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "4ceef691e8b08497be1354e20f5c80d5fff71c54eacb5f356297b12a87e524c3"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6302e51443dbf759cac2fcfa2185f5c84e4c9cb5"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "45382fd53971ca05b44ab998f445bbb0e244c5a2fded0b13dc86284bdf2381e5"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8a5c080275411239edbce40a93c2085f25626986"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "7292e2c89b8b680a607013529aeb743579d596ef27fcd6c64cdd45f7a03edba4"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "f2da6d4dd0a4a165ff7481bf61f3f56c0da63d97"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "87ff05d8d519bd30bccbcb1f0ace9b381da451d11e578948d47ce546dc52bc24"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "5bc3d838c487c17c7ce576b0a05d2716ea41fe54"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "9dd6ac3976a23f0e603295d010c350afdb689ac5ba26b07f4732513a97658ef9"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "5f88cd35f2f525aebc07ea7fb29344d65b986962"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "c9b08645779c795d8f38b862296ed77bcbd3c96bedb2aabd426d74d80380e4d6"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "07d99f48ed86e927af845488c4ff70734cf13451"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "ea4337568f10bcea4c5700119198150432d8b7bcdafb002406998fcab1de6ceb"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "7fb86d65adb118d965ec1f8e2c76b42d79e6c957"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e2c4ffc90b81042696f669beff918c4c4872c32a51eaf0906e865709e7d299e7"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "561f31e669b19006b1f290ca14afd29733793045"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "fc6830839c5ec9c1064d4ab8543f92341e8a2c1e306a2e58b40f6c61eb572831"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+5/LibUnwind.v1.3.2.x86_64-unknown-freebsd.tar.gz"
