[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "8e0b9cf97a65721a13d34133d00a8e254f01696d"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "bf80a11762e087b8c3aaba1c8c8eb260e37f3c8e6ad2229ed9b35741e5a4fcf8"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "e7aff6f61af3aacbc2fa368c0b5d9ce625bf3264"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "e92d1c2b46a5e72df2419e138127e8a437b0f9e2a3835c54a595d91af91c6365"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "fb52ea9f0c5b064dbe6851197979e332500b24ec"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "e2bde0007bee54434310d4e78a587508368f06226b453b5370cdd431abed6309"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.aarch64-unknown-freebsd.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4002b3b9bfbfde81c7da433622a9e79152c9bc63"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "f032e381830fdce53b5281a55158814226ef0d45df0991a44779c55750e84d0d"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d1223cb6f2ee34e7c9f3513f3311a25cea3ae7d2"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "4c75543501fbced88efaa2bc4520ccb2aa7ab1f58c3f7a8a0aa3e5d9b9f2babd"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e24a19bcbc4899b42f43ed73ca099b5d390d1aa2"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "a18b014c801166af91caa6a0b9c3a05b747312bbb7386975cd45f4d50ee2acd9"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9a3e9df62b7c673d18bdfc22dfd02f23d4997e2a"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "ac8ba87f7871a8006f00890fc84ee506f83145c69dedd76f4a7e0529e1bdbed4"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "f9bdf2a6ab1095990237010fdbbf6104c6f5d381"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "544ac287bb513c6af4164a607c24e807a821fc524ab1fa49c7b402ab26d05a63"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "732a42a69cd80d16c35a5d4cae55704a7d2f8ec1"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "519d3296d16388882599f009c350552f2700c5b45e1ae1168a156bee75f55967"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "54a9f4547d18a407282446131fe877ff5a7b5d1f"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "29a7fe3181d72ef16ecd1479d9627e710094f17788b6a3b54c0b41715e68240f"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "riscv64"
git-tree-sha1 = "951638b4ef17ddde9239a9ad20fa159a11d48cb1"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "00e210311329d2f72b05657dc16182458f1b9de324133fb54dd9647dea7de974"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.riscv64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "2c379b51f498859d86710ba7d00df42416a120a8"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "020ab9cd07fcb1aac2abeb05049511b868144b2bfd3915e6f5c83a2414ff6904"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "99cd043a8167844f02b0eb5a3ab55a003514b6f8"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibUnwind.download]]
    sha256 = "4fe3227445af8f512abba3b9efa3174b82536dffbbb56860329b04997e3a9dfa"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "840d34f5aa28ef4be595229922028c4a55dcc263"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "41dc7531b3d8dd0676edb4aa28a63a882316d7f22a684d9fff9e666dd770980a"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "ba33176ef8f143688dcb74225f806125373b7f88"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "2f09dc43bc05e4d63aa015e4bc0f0887166411a8e9a75808abde00415f6a1f51"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.8.2+0/LibUnwind.v1.8.2.x86_64-unknown-freebsd.tar.gz"
