[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "4b7b1ccf25c9917cb2b735b55373f6b5d3439030"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "2fbf981e6212cfdf5d68a111a4380502e006f5a0c11d93885de003647cc4fb88"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.aarch64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "aarch64"
git-tree-sha1 = "96b53ef8a0fffd88ac1212895801cd723bd0627e"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "ff905d6bffe0df7a8b7122187332cc347f9c95d77c550031c1c775a03ecddca0"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.aarch64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3f656c5ef2a0c90b0fd80c11a2b4f9273c185842"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "2de0ddbc280614ff74c63cef627c515e3d67e77fe5a92524b471096ebf9cc860"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.armv6l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e1a21831b9874b2d6c5f4e2155ebb7a75670411"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "0e5f47249a6224805a9d833b18a6d3adef3a7fa9802469f63bf5028b170afde1"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.armv6l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bcbfd5f402882e9ef937e51f3c2c81c736e60f08"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "982f88dbee2db86f136eed314ff5e2430a26fb99d3e651c7e3d1851201e30b49"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.armv7l-linux-gnueabihf.tar.gz"
[[LibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ca69802dfb2ce36d5815e25ea7fd389cd3fb85a"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "c8fd635db3abb141b62f22c3aa4ce3c27e715058e7173d6290a165780b872977"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.armv7l-linux-musleabihf.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "17e9a9b29f7b2658731b898b07e6d4cab2faefac"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "6e86ac00ff65c56dfb61ead960cb3506b34e715afb3331c8f6c8ef5a7361501f"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.i686-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "i686"
git-tree-sha1 = "3b20aa5f077e1101a901d7bdf46f3b8055cc5849"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "fc665962b642c8e271b113b4a69c18fbee7cecd384a328811ebb55f583611343"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.i686-linux-musl.tar.gz"
[[LibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "ff45f38c5632133d3c418e5583da701cfc8156b3"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "16f8e3f7b1f72dffa6ea4b793a1e34c23bdc95a9512818fb6fd334c10159acf2"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.powerpc64le-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "8a0f7804d12ca8e9a8ec6e1c9fa802f3b8f14b30"
libc = "glibc"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "d204642963b7203739674d42b55940d754ecfebf62ee45e167b68ce76d8e5de5"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.x86_64-linux-gnu.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "b1fdd7add58c506de35f332bd9e1241d6392f50b"
libc = "musl"
os = "linux"

    [[LibUnwind.download]]
    sha256 = "9bd1eae794bd79a388844726e2b0f19c4d038f0a19ad03e6696ab931b7f5e815"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.x86_64-linux-musl.tar.gz"
[[LibUnwind]]
arch = "x86_64"
git-tree-sha1 = "d5d415e2274565d09513c4c193a35c440e12312a"
os = "freebsd"

    [[LibUnwind.download]]
    sha256 = "4f04b4e08df5d775343aca334eaf80b5768d32207afa7b999aba69841533daa6"
    url = "https://github.com/JuliaBinaryWrappers/LibUnwind_jll.jl/releases/download/LibUnwind-v1.3.2+2/LibUnwind.v1.3.2.x86_64-unknown-freebsd.tar.gz"
